[package]
name = "ls-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.39",features = ["derive"]}
owo-colors = "4.2.1"
strum = {version = "0.27",features = ["derive"]}
strum_macros = "0.27"
tabled = "0.20.0"
chrono = "0.4.41"